-- Proactive cloud digests: short, periodic briefs the GMI cloud agent writes for a
-- user without being asked. A "morning_brief" summarizes the day ahead (today's
-- calendar events + open tasks); an "evening_recap" summarizes what changed today
-- (completed tasks, new comments, what's still open).
--
-- These are generated by a scheduled batch run (src/scripts/run-digests.ts) or on
-- demand (POST /api/v1/digests/run) and read back by the apps. The cloud agent runs
-- on GMI MaaS (see docs/agentbox/DIGESTS.md). Source of truth = backend Postgres,
-- same as tasks/comments, so iOS and Mac render the identical digest.

CREATE TABLE IF NOT EXISTS digests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    kind VARCHAR(20) NOT NULL CHECK (kind IN ('morning_brief', 'evening_recap')),
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    -- How the body was produced: 'gmi' = written by the GMI model; 'fallback' = the
    -- model was unreachable so we rendered a deterministic local summary; 'empty' =
    -- nothing to report, so we skipped the model call entirely (saves credits).
    source VARCHAR(20) NOT NULL DEFAULT 'gmi' CHECK (source IN ('gmi', 'fallback', 'empty')),
    model VARCHAR(120),
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_digests_user_id_created_at ON digests(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_digests_kind ON digests(kind);
