-- Structured agent run-state on the task itself — the gap vs OpenClaw's Workboard
-- `execution` record (docs/rebuild/19-TASKS-VS-WORKBOARD.md, P1). Today "an agent is
-- working this task right now" lives only as a chat comment; this promotes it to
-- structured state ON the task so the UI can show it (TaskRuntimeBadge) without
-- string-parsing a comment body.
--
-- All columns nullable + additive (ADD COLUMN IF NOT EXISTS), so this is idempotent
-- and safe to re-run. Mirrors migration 015's `assigned_runtime` column-add pattern.
--
-- Source of truth for "is this task being worked, and how did the last run end" =
-- these columns. run_status lifecycle: NULL/idle -> running (set on dispatch) ->
-- done | review | blocked (terminal, set on completion).
--   running  — a run is in flight (run_id/run_started_at stamped)
--   review   — run finished, left a comment for the human to review
--   blocked  — run could not complete (service unreachable / not configured)
--   done     — run completed the task
--   idle     — explicit reset back to no active run

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS run_status TEXT
    CHECK (run_status IS NULL OR run_status IN ('idle', 'running', 'review', 'blocked', 'done'));

-- Identifier for the current/last run (generated by the dispatch route). Lets the
-- client correlate a run with the comment it produced and detect a newer run.
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS run_id TEXT;

-- Live session handle (Workboard's card->session duality). Reserved for P2's
-- "Open conversation" jump; left NULL by the cloud-agent dispatch (no live session).
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS session_key TEXT;

-- When the current/last run started, and the last heartbeat from it. The heartbeat
-- column is the hook for P3 stale-run detection; cloud dispatch stamps it at start
-- and at completion.
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS run_started_at TIMESTAMPTZ;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS run_last_heartbeat_at TIMESTAMPTZ;
